#!/usr/bin/env bash
# a Bash script that installs nginx a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restart
