#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx start
