#!/usr/bin/env bash
# Bash script that prints 1 to 20
a=1;
while [ $a -lt 21 ];
do
    if [ "$a" -eq 4 ]; then
        echo "$a"
        echo "bad luck from China"
    elif [ "$a" -eq 9 ]; then
        echo "$a"
        echo "bad luck from Japan"
    elif [ "$a" -eq 17 ]; then
        echo "$a"
        echo "bad luck from Italy"
    else 
        echo "$a";
    fi
    ((a++));
done;